### PR TITLE
A fix for the installation blues

### PR DESCRIPTION
**Pull request by JJ**
Which will help many other modules downstream.

### CODE REVIEW

**Comment by JJ** [comment]
Ping? I'd be willing to help you manage this distribution, or adopt it into Raku community modules, if you don't have the time...

**Comment by retupmoca** [comment]
Merged! I'm not very involved with Raku stuff these days, so if I go radio-silence again, I'd be happy to have this adopted into the community modules (rather than you having to wait nearly a year - sorry about that!)

**Comment by JJ** [comment]
> Merged! I'm not very involved with Raku stuff these days, so if I go radio-silence again, I'd be happy to have this adopted into the community modules (rather than you having to wait nearly a year - sorry about that!)

Nowadays I'm more for having someone adopt it than dumping it into community modules... of which there are already a hundred. So if you give me the commit bit, I'll try to do my best to support it.

**Comment by retupmoca** [comment]
Makes sense to me - you should have an invite now

**Pull request merged**
